# Generated by Django 4.2.4 on 2023-08-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_record_description_record_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
